spring.application.name=happypour
spring.app.address=${SPRING_APP_ADDRESS}
spring.profiles.active=default
debug=false
spring.web.resources.static-locations=classpath:/static/dist
jwt.secret=${SPRING_JWT_SECRET}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/drop tables at startup/shutdown, USE "update" FOR THE DATA TO PERSIST.
spring.jpa.hibernate.ddl-auto=${SPRING_DDL_AUTO}

# Optional: Use the following for better logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Enable logging for Spring security
logging.level.org.springframework.security=DEBUG
logging.level.com.happypour=DEBUG

# Enable detailed logging for JWT authentication filter class
logging.level.com.happypour.security.filter.JwtAuthenticationFilter=DEBUG

# Request/Response logging for incoming HTTP requests
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# email
#spring.mail.host=${SPRING_MAIL_HOST}
#spring.mail.port=2525
#spring.mail.username=${SPRING_MAIL_USERNAME}
#spring.mail.password=${SPRING_MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# React Frontend
happypour.app.address=${REACT_APP_ADDRESS}
