
services:
  backend:
    container_name: happy-pour-app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose backend on port 8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
